apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notifications
  name: notifications
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications
  template:
    metadata:
      labels:
        app: notifications
    spec:
      containers:
        - image: asia-southeast1-docker.pkg.dev/sleepr-387607/notifications/production
          name: notifications
          env:
            - name: PORT
              value: '3000'
          port: 
            - containerPort: 3000
