version: '3.8'

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    command: yarn run start:dev reservations
    env_file:
      - ./apps/reservations/.env
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app
  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: yarn run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports: 
      - 3001:3001
    volumes:
      - .:/usr/src/app
  notifications:
    build:
      context: .
      dockerfile: ./apps/notifications/Dockerfile
      target: development
    command: yarn run start:dev notifications
    env_file:
      - ./apps/notifications/.env
    volumes:
      - .:/usr/src/app
  mongo:
    container_name: mongo-sleepr
    image: mongo:latest
    restart: always
    environment:
      - MONGO_DATABASE="sleepr"
    ports:
      - 27017:27017

  mongo-express:
    container_name: mongo-sleepr-express
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
    depends_on:
      - mongo
    ports:
      - 7200:8081